name: Update Rules
on: 
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
jobs:
  run_shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Update uBLACKLIST
        run: |
          bash ./gen.sh
      - name: Git push assets to Github and Coding
        run: |
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git branch -m main
          git add --all
          git commit -m "Updated at $(date)"
          git remote set-url origin git@github.com:MohamedElashri/ublacklist.git
          git push https://$USERNAME:$REPO_KEY@github.com/MohamedElashri/ublacklist.git
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          USERNAME: github-actions[bot]
